### ISSUE TITLE
Image after video is done playing

### ISSUE THREAD

**Issue by mfahem** [pupunzi/jquery.mb.YTPlayer#354]
Hello,

I am playing the video once (by setting loop to false) but I would like to have a background image at the end of the video. How can I achieve that please ?

Thanks :)

**Comment by pupunzi** [comment]
Hi,
you can just add a background image via CSS to the element you are instancing the background video.

If the YTPlayer is instanced for the body you can add a background as follow in your css:

```css
body {
      background-image: url("[path to the background inage]");
      background-position: center center;
      background-repeat: no-repeat;
      background-size: cover;
}
```
